package cinema.utils;

public enum PageType {
    MAIN_MANAGE_SCREENINGS,
        MANAGE_SCREENING,
            SHOW_SCREENING_SEAT_LAYOUT,
            ADD_RESERVATION,
            DELETE_RESERVATION,
            EDIT_SCREENING_THEATER,
            EDIT_SCREENING_SHOW,
            EDIT_SCREENING_EXPERIENCE_TYPE,
        ADD_SCREENING,
        DELETE_SCREENING,
    MAIN_THEATER_EDITOR,
        MANAGE_THEATER,
            SHOW_THEATER_SEAT_LAYOUT,
            EDIT_THEATER_NAME,
            EDIT_THEATER_DIMENSIONS,
            SET_CURRENT_SCREENING, 
        ADD_THEATER,
        DELETE_THEATER,
    MAIN_SHOW_EDITOR,
            MANAGE_SHOW_MOVIE,
                EDIT_MOVIE_LEAD_ACTOR,
            MANAGE_SHOW_ANIMATED_MOVIE,
                EDIT_ANIMATED_MOVIE_ANIMATION_STUDIO,
            MANAGE_SHOW_CONCERT_FILM,
                EDIT_CONCERT_FILM_ARTIST,
                
                EDIT_SHOW_TITLE,
                EDIT_SHOW_DESCRIPTION,
                EDIT_SHOW_RELEASE_YEAR,
                EDIT_SHOW_DURATION,
        ADD_SHOW,
            SELECT_SHOW_TYPE,
                ADD_SHOW_MOVIE,
                ADD_SHOW_ANIMATED_MOVIE,
                ADD_SHOW_CONCERT_FILM,
        DELETE_SHOW;
}
